name: AntiAutoFish
version: '${project.version}'
main: me.esmee.antiautofish.AntiAutoFish
author: sadesmee
commands:
  antiautofish:
    description: AntiAutoFish toggle command
    aliases: [aaf]
    usage: /<command>