name: AntiAutoFish
version: '1.0-SNAPSHOT'
main: me.esmee.antiautofish.AntiAutoFish
author: sadesmee
commands:
  antiautofish:
    description: AntiAutoFish toggle command
    aliases: [aaf]
    usage: /<command>